import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { Button } from '@/components/ui/button';
import { Save, Eye, EyeOff, BarChart3, TrendingUp } from 'lucide-react';
export const BudgetGridHeader = ({ year, hasChanges, loading, budgetData, restaurantName, onSave, viewMode = 'budget', onToggleViewMode, showOnlySummary = false, onToggleSummary }) => {
    const calculateTotal = () => {
        return budgetData.reduce((sum, row) => sum + (row.total || 0), 0);
    };
    const formatCurrency = (value) => {
        return `€${value.toLocaleString('es-ES')}`;
    };
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-semibold text-gray-900", children: ["Presupuesto Anual ", year] }), restaurantName && (_jsx("p", { className: "text-sm text-gray-600 mt-1", children: restaurantName }))] }), _jsx("div", { className: "flex items-center gap-3", children: _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Total Presupuestado" }), _jsx("p", { className: "text-lg font-semibold text-gray-900", children: formatCurrency(calculateTotal()) })] }) })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center gap-3", children: [onToggleViewMode && (_jsxs(_Fragment, { children: [_jsxs(Button, { onClick: () => onToggleViewMode('budget'), variant: viewMode === 'budget' ? 'default' : 'outline', className: "flex items-center gap-2", children: [_jsx(Eye, { className: "w-4 h-4" }), "Presupuesto"] }), _jsxs(Button, { onClick: () => onToggleViewMode('comparison'), variant: viewMode === 'comparison' ? 'default' : 'outline', className: "flex items-center gap-2", children: [_jsx(BarChart3, { className: "w-4 h-4" }), "Mostrar Comparativa"] }), _jsxs(Button, { onClick: () => onToggleViewMode('actuals'), variant: viewMode === 'actuals' ? 'default' : 'outline', className: "flex items-center gap-2", children: [_jsx(TrendingUp, { className: "w-4 h-4" }), "Mostrar Reales"] })] })), onToggleSummary && (_jsxs(Button, { onClick: onToggleSummary, variant: "outline", className: "flex items-center gap-2", children: [showOnlySummary ? _jsx(Eye, { className: "w-4 h-4" }) : _jsx(EyeOff, { className: "w-4 h-4" }), showOnlySummary ? 'Mostrar Detalle' : 'Mostrar Resumen'] }))] }), _jsxs("div", { className: "flex items-center gap-3", children: [hasChanges && (_jsx("span", { className: "text-sm text-amber-600 font-medium", children: "Cambios sin guardar" })), _jsxs(Button, { onClick: onSave, disabled: !hasChanges || loading, className: "flex items-center gap-2", children: [_jsx(Save, { className: "w-4 h-4" }), loading ? 'Guardando...' : 'Guardar Cambios'] })] })] })] }));
};
