// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = "https://ckvqfrppnfhoadcpqhld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdnFmcnBwbmZob2FkY3BxaGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzg0OTgsImV4cCI6MjA2NTcxNDQ5OH0.5FfO-Nr8L01EwjPI_gf6rG2xucCLjRBQWAZzcXZsSAQ";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
